### ISSUE TITLE
OverflowError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by prabakarsukumar** [jrkerns/pylinac#140]
**Pylinac CBCT analysis show the overflow error for most of CBCT images I have copied the error 
It was working fine for few days and after that I got this error which i cant able to identify the error**

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python36-32\lib\tkinter\__init__.py", line 1702, in __c
all__
    return self.func(*args)
  File "C:\Python\venv\lib\site-packages\pylinac\py_gui.py", line 199, in analyz
e_cbct
    cat = getattr(ct, self.ct_catphantype.get()).from_zip(self.ct_file.get())
  File "C:\Python\venv\lib\site-packages\pylinac\ct.py", line 926, in from_zip
    obj = cls(temp_zip, check_uid=check_uid)
  File "C:\Python\venv\lib\site-packages\pylinac\ct.py", line 886, in __init__
    self.dicom_stack = image.DicomImageStack(folderpath, check_uid=check_uid)
  File "C:\Python\venv\lib\site-packages\pylinac\core\image.py", line 973, in __
init__
    if self.is_CT_slice(path):
  File "C:\Python\venv\lib\site-packages\pylinac\core\image.py", line 1006, in i
s_CT_slice
    ds = pydicom.dcmread(file, force=True, stop_before_pixels=True)
  File "C:\Python\venv\lib\site-packages\pydicom\filereader.py", line 886, in dc
mread
    force=force, specific_tags=specific_tags)
  File "C:\Python\venv\lib\site-packages\pydicom\filereader.py", line 765, in re
ad_partial
    specific_tags=specific_tags)
  File "C:\Python\venv\lib\site-packages\pydicom\filereader.py", line 408, in re
ad_dataset
    raw_data_element = next(de_gen)
  File "C:\Python\venv\lib\site-packages\pydicom\filereader.py", line 283, in da
ta_element_generator
    value = fp_read(length)
OverflowError: cannot fit 'int' into an index-sized integer

Thanks

**Comment by jrkerns** [comment]
This is an issue with pydicom and your DICOM files (note the pydicom in the traceback). I would submit an issue there: https://github.com/pydicom/pydicom/issues.
