### ISSUE TITLE
FlatSym

### ISSUE THREAD

**Issue by wosane** [jrkerns/pylinac#152]
I just downloaded the v2.2 of pylinac but the flatsym module is not working 
this is what the error i am getting
Any suggestion please
thank you

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wneeranj\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:/Users/wneeranj/PycharmProjects/tg142/linacqa.py", line 106, in fs
    my_img.analyze(flatness_method='varian', symmetry_method='varian', vert_position=0.5, horiz_position=0.5)
  File "C:\Users\wneeranj\tg142\lib\site-packages\pylinac\flatsym.py", line 139, in analyze
    self.flatness = self._calc_flatness(flatness_method, vert_position, horiz_position)
  File "C:\Users\wneeranj\tg142\lib\site-packages\pylinac\flatsym.py", line 186, in _calc_flatness
    vert_flatness, vert_max, vert_min, vert_lt, vert_rt = flatness_calculation(vert_profile)
  File "C:\Users\wneeranj\tg142\lib\site-packages\pylinac\flatsym.py", line 19, in flatness_varian
    dmax = profile.field_calculation(field_width=0.8, calculation='max')
  File "C:\Users\wneeranj\tg142\lib\site-packages\pylinac\core\decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\wneeranj\tg142\lib\site-packages\pylinac\core\profile.py", line 490, in field_calculation
    return field_values.max()
  File "C:\Users\wneeranj\tg142\lib\site-packages\numpy\core\_methods.py", line 28, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by wosane** [comment]
Thank you James
On one computer I have pylinac  version 2.1.0.1 running and it uses BeamImage and that work fine with the image file i have
On a different computer i have version 2.2 running and when i use FlatSym and .analyse, it  is giving me an error  using the  same image file 
I am not sure whether it is looking at the size of the image array 
The only thing i know is that the panel has a half res(768x384) not sure whether that has something to do with it.
thank you again

**Comment by jrkerns** [comment]
Send me the image and I'll take a look. Thanks

**Comment by Zarita78** [comment]
Hi,
I also have the very same problem using FlatSym with the latest version of pylinac. I haven't found  this issue with BeamImage in the past. I have tested it on the same images and I got the error above. It only seemed to work for one of the images but plots on the pdf appeared up side down. 
Any advice would be appreciate it. Thanks very much.
