### ISSUE TITLE
Low res images incorrectly inverted in FlatSym module

### ISSUE THREAD

**Issue by alanphys** [jrkerns/pylinac#263]
**Describe the bug**
image.check_inversion incorrectly inverts low resolution images.

**To Reproduce**
From python console:
`from pylinac import FlatSym`
`fs = FlatSym('LowRes.dcm')`
`fs.analyze('varian', 'varian')`

causes traceback because the peak cannot be found because the image has been incorrectly inverted. Image LowRes.dcm is attached below as a zip file.

**Expected behavior**
fs.analyze('varian', 'varian') should complete without error.

**Workaround**
Setting line 113 of flatsym.py to self.image.check_inversion(box_size=1) gives the correct inversion, but will not work if there are burn markers in the corners.

A more correct approach would be to express the box_size as a ratio of the image size and not in pixels.

or possibly use check_inversion_by_histogram. What are your thoughts?
[LowRes.zip](https://github.com/jrkerns/pylinac/files/3868671/LowRes.zip)

**Additional context**
Traceback (most recent call last):
  File "/pylinac/pylinac/core/profile.py", line 237, in _get_initial_peak
    initial_peak = initial_peak_arr[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/pylinac/pylinac/flatsym.py", line 145, in analyze
    self.symmetry = self._calc_symmetry(symmetry_method, vert_position, horiz_position)
  File "/pylinac/pylinac/flatsym.py", line 207, in _calc_symmetry
    vert_sym, vert_sym_array, vert_lt, vert_rt = symmetry_calculation(vert_profile)
  File "/pylinac/pylinac/flatsym.py", line 43, in symmetry_point_difference
    values = profile.field_values(field_width=0.8)
  File "/pylinac/pylinac/core/decorators.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/pylinac/pylinac/core/profile.py", line 439, in field_values
    left, right = self.field_edges(field_width)
  File "/pylinac/pylinac/core/decorators.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/pylinac/pylinac/core/profile.py", line 455, in field_edges
    fwhmc = self.fwxm_center(interpolate=interpolate)
  File "/pylinac/pylinac/core/profile.py", line 371, in fwxm_center
    fwxm = self.fwxm(x, interpolate=interpolate)
  File "/pylinac/pylinac/core/profile.py", line 359, in fwxm
    li = self._penumbra_point(LEFT, x, interpolate)
  File "/pylinac/pylinac/core/decorators.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/pylinac/pylinac/core/profile.py", line 275, in _penumbra_point
    peak = copy.copy(self._initial_peak_idx)
  File "/pylinac/pylinac/core/profile.py", line 214, in _initial_peak_idx
    x_idx = self._get_initial_peak(self._passed_initial_peak)
  File "/pylinac/pylinac/core/profile.py", line 243, in _get_initial_peak
    raise ValueError("A reasonable initial peak was not found in the profile. Ensure peak is not at profile edge")
ValueError: A reasonable initial peak was not found in the profile. Ensure peak is not at profile edge

**Comment by jrkerns** [comment]
`image.check_inversion_by_historgram` will correctly determine the inversion. Will switch to that as well as add an 'invert' parameter to analyze to override the inversion. The current workaround would be to do the following:

`fs = FlatSym(...)`
`fs.image.check_inversion_by_histogram()`
`fs.analyze(...)`
